src/Entity/Attempt.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AttemptRepository")
 */
class Attempt
{
    use BaseTrait;

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="bigint")
     */
    private $id;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Example", mappedBy="attempt", orphanRemoval=true)
     */
    private $examples;

    /**
     * @ORM\Column(type="datetime")
     */
    private $addTime;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Session", inversedBy="attempts")
     * @ORM\JoinColumn(nullable=false)
     */
    private $session;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Task", inversedBy="attempts")
     */
    private $task;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Settings", inversedBy="attempts")
     * @ORM\JoinColumn(nullable=false)
     */
    private $settings;

    public function __construct()
    {
        $this->examples = new ArrayCollection();
        $this->addTime = new \DateTime();
    }

    public function getId()
    {
        return $this->id;
    }

    /**
     * @return Collection|Example[]
     */
    public function getExamples(): Collection
    {
        return $this->examples;
    }

    public function addExample(Example $example): self
    {
        if (!$this->examples->contains($example)) {
            $this->examples[] = $example;
            $example->setAttempt($this);
        }

        return $this;
    }

    public function removeExample(Example $example): self
    {
        if ($this->examples->contains($example)) {
            $this->examples->removeElement($example);
            // set the owning side to null (unless already changed)
            if ($example->getAttempt() === $this) {
                $example->setAttempt(null);
            }
        }

        return $this;
    }

    public function getAddTime(): ? \DateTimeInterface
    {
        return $this->dt($this->addTime);
    }

    public function setAddTime(\DateTimeInterface $addTime): self
    {
        $this->addTime = $addTime;

        return $this;
    }

    public function getSession(): ? Session
    {
        return $this->session;
    }

    public function setSession(? Session $session): self
    {
        $this->session = $session;

        return $this;
    }

    public function getExamplesCount()
    {
        return $this->getSettings()->getExamplesCount();
    }

    public function getLimitTime()
    {
        return $this->dts($this->getAddTime()->getTimestamp() + $this->getSettings()->getDuration());
    }

    public function getMaxTime()
    {
        return $this->dts($this->getSettings()->getDuration());
    }

    public function getUser()
    {
        return $this->getSession()->getUser();
    }

    public function getTask(): ?Task
    {
        return $this->task;
    }

    public function setTask(?Task $task): self
    {
        $this->task = $task;

        return $this;
    }

    public function getSettings(): ?Settings
    {
        return $this->settings;
    }

    public function setSettings(?Settings $settings): self
    {
        $this->settings = $settings;

        return $this;
    }
}

src/Controller/HomeworkController.php
<?php

namespace App\Controller;

use App\Entity\Task;
use App\Repository\AttemptRepository;
use App\Repository\ExampleRepository;
use App\Repository\TaskRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/homework")
 */
class HomeworkController extends AbstractController
{
    use BaseTrait;

    /**
     * @Route("/", name="homework_index")
     */
    public function index(TaskRepository $taskRepository, AttemptRepository $attemptRepository): Response
    {
        $this->denyAccessUnlessGranted('SHOW_HOMEWORKS');

        $tasks = $taskRepository->findHomeworkByCurrentUser();
        $activeTasks = $archiveTasks = [];

        foreach ($tasks as $task) {
            $group = $this->isGranted('SOLVE', $task) ? 'activeTasks' : 'archiveTasks';
            ($$group)[] = $task;
        }

        return $this->render('homework/index.html.twig', [
            'activeTasks' => $activeTasks,
            'archiveTasks' => $archiveTasks,
            'attemptRepository' => $attemptRepository,
        ]);
    }

    /**
     * @Route("{id}/solve", name="homework_solve")
     */
    public function solve(Task $task, AttemptRepository $attemptRepository): Response
    {
        $this->denyAccessUnlessGranted('SOLVE', $task);

        return $this->redirectToRoute('attempt_solve', [
            'id' => $attemptRepository->getNewByCurrentUserAndTask($task)->getId(),
        ]);
    }

    /**
     * @Route("{id}/examples", name="homework_examples")
     */
    public function examples(Task $task, ExampleRepository $exampleRepository): Response
    {
        $this->denyAccessUnlessGranted('SHOW_EXAMPLES', $task);

        return $this->render('homework/examples.html.twig', [
            'task' => $task,
            'examples' => $exampleRepository->findByCurrentUserAndHomework($task),
        ]);
    }

    /**
     * @Route("{id}/attempts", name="homework_attempts")
     */
    public function attempts(Task $task, AttemptRepository $attemptRepository): Response
    {
        $this->denyAccessUnlessGranted('SHOW_ATTEMPTS', $task);

        return $this->render('homework/attempts.html.twig', [
            'task' => $task,
            'attempts' => $attemptRepository->findByCurrentUserAndHomework($task),
        ]);
    }
}

templates/homework/attempts.html.twig
{% extends "homework/base.html.twig" %}

{%block title "Архив попыток ("~task.settings.description~")"%}

{% block main %}
<h1>Архив попыток</h1>
{{ include("attempt/index_table.html.twig") }}
{% endblock %}

{% block javascripts %}
{{parent()}}
<script src="/js/jquery.datatables.min.js"></script>
<script>
$("table").DataTable({
searching: false,
sorting: false,
data: {{processAttempts(attempts)|reverse|json_encode|raw}},
deferRender: true,
pageLength: 50,
language: {{include("attempt/language.json.twig")}}
});
</script>
{% endblock %}

templates/homework/base.html.twig
{% extends 'main.html.twig' %}

{% block bottom_links %}
<a href="{{ path('homework_index') }}">Назад к домашнему заданию</a>
{% endblock %}

templates/homework/examples.html.twig
{% extends "homework/base.html.twig" %}

{% block title "Архив примеров ("~task.settings.description~")" %}

{% block main %}
<h1>Архив примеров</h1>
{{ include('student/examples_table.html.twig') }}
{% endblock %}

{% block javascripts %}
{{ parent() }}
<script src="/js/jquery.datatables.min.js"></script>
<script>
$("table").DataTable({
searching: false,
sorting: false,
data: {{processExamples(examples)|reverse|json_encode|raw}},
deferRender: true,
pageLength: 50,
language: {{include("example/language.json.twig")}}
});
</script>
{% endblock %}

templates/homework/index.html.twig
{% extends 'homework/base.html.twig' %}

{% block title %}Домашнее задание{% endblock %}

{% block main %}
<h1>Домашнее задание</h1>

{% from 'homework/tasks_table.html.twig' import tasks_table as tasks %}
{{ tasks("Активные задания", activeTasks, attemptRepository) }}
{{ tasks("Архив заданий", archiveTasks, attemptRepository) }}
{% endblock %}

{%block javascripts%}
{{parent()}}
<script src="/js/jquery.datatables.min.js"></script>
<script>
    hideHomeworksBlock();
    
    $("table").DataTable({
        pageLength: 25,
        //order: [1, "asc"],
        lengthMenu: [25, 50, 100, 250],
        language: {{ include("task/language.json.twig") }}
    });
</script>
{%endblock%}

templates/homework/tasks_table.html.twig
{% macro tasks_table(title, tasks, attemptRepository) %}
<h2>{{ title }}</h2>

<table class="table">
    <thead>
        <tr>
            <th>№</th>
            <th>Задание</th>
            <th>Количество повторений</th>
            <th>Время добавления</th>
            <th>Время окончания</th>
            <th>Попытки (Выполненные / Начатые)</th>
            <th>Средняя оценка (Выполненные / Начатые)</th>
            <th>Действия</th>
        </tr>
    </thead>
    <tbody>
        {% for number, task in sortByAddTime(tasks)|reverse %}
        <tr>
            <td>{{ number + 1 }}</td>
            <td><a href="{{ path('settings_show', {'id': task.settings.id}) }}">{{ task.settings.description }}</a></td>
            <td>{{ task.timesCount }}</td>
            <td>{{ task.addTime }}</td>
            <td>{{ task.limitTime }}</td>
            <td>{{ attemptRepository.findDoneByCurrentUserAndTask(task)|length }} / {{
                attemptRepository.countByCurrentUserAndTask(task) }}</td>
                {% set doneRating = attemptRepository.getDoneAverageRatingByCurrentUserAndTask(task) %}
                {% set rating = attemptRepository.getAverageRatingByCurrentUserAndTask(task) %}
            <td>{{ doneRating ? doneRating|round : '-' }} / {{ rating ? rating|round : '-' }}</td>
            <td>
                <a href="{{ path('homework_attempts', {'id': task.id}) }}">Посмотреть попытки</a>
                <a href="{{ path('homework_examples', {'id': task.id}) }}">Посмотреть список примеров</a>
                {% if is_granted('SOLVE', task) %}
                <a href="{{ path('homework_solve', {'id': task.id}) }}" role="button">Выполнить</a>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{%endmacro %}