src/Entity/Attempt.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AttemptRepository")
 */
class Attempt
{
    use BaseTrait;

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="bigint")
     */
    private $id;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Example", mappedBy="attempt", orphanRemoval=true)
     */
    private $examples;

    /**
     * @ORM\Column(type="datetime")
     */
    private $addTime;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Session", inversedBy="attempts")
     * @ORM\JoinColumn(nullable=false)
     */
    private $session;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Task", inversedBy="attempts")
     */
    private $task;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Settings", inversedBy="attempts")
     * @ORM\JoinColumn(nullable=false)
     */
    private $settings;

    public function __construct()
    {
        $this->examples = new ArrayCollection();
        $this->addTime = new \DateTime();
    }

    public function getId()
    {
        return $this->id;
    }

    /**
     * @return Collection|Example[]
     */
    public function getExamples(): Collection
    {
        return $this->examples;
    }

    public function addExample(Example $example): self
    {
        if (!$this->examples->contains($example)) {
            $this->examples[] = $example;
            $example->setAttempt($this);
        }

        return $this;
    }

    public function removeExample(Example $example): self
    {
        if ($this->examples->contains($example)) {
            $this->examples->removeElement($example);
            // set the owning side to null (unless already changed)
            if ($example->getAttempt() === $this) {
                $example->setAttempt(null);
            }
        }

        return $this;
    }

    public function getAddTime(): ? \DateTimeInterface
    {
        return $this->dt($this->addTime);
    }

    public function setAddTime(\DateTimeInterface $addTime): self
    {
        $this->addTime = $addTime;

        return $this;
    }

    public function getSession(): ? Session
    {
        return $this->session;
    }

    public function setSession(? Session $session): self
    {
        $this->session = $session;

        return $this;
    }

    public function getExamplesCount()
    {
        return $this->getSettings()->getExamplesCount();
    }

    public function getLimitTime()
    {
        return $this->dts($this->getAddTime()->getTimestamp() + $this->getSettings()->getDuration());
    }

    public function getMaxTime()
    {
        return $this->dts($this->getSettings()->getDuration());
    }

    public function getUser()
    {
        return $this->getSession()->getUser();
    }

    public function getTask(): ?Task
    {
        return $this->task;
    }

    public function setTask(?Task $task): self
    {
        $this->task = $task;

        return $this;
    }

    public function getSettings(): ?Settings
    {
        return $this->settings;
    }

    public function setSettings(?Settings $settings): self
    {
        $this->settings = $settings;

        return $this;
    }
}

src/Controller/AttemptController.php
<?php

namespace App\Controller;

use App\Entity\Attempt;
use App\Form\SettingsType;
use App\Repository\AttemptRepository;
use App\Repository\ExampleRepository;
use App\Repository\ProfileRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/attempt")
 */
class AttemptController extends Controller
{
    use BaseTrait;

    /**
     * @Route("/", name="attempt_index")
     */
    public function index(AttemptRepository $attemptRepository): Response
    {
        return $this->render('attempt/index.html.twig', [
            'attempts' => $attemptRepository->findAllByCurrentUser(),
        ]);
    }

    /**
     *@Route("/{id}/show", name="attempt_show", requirements={"id": "\d+"})
     */
    public function show(Attempt $attempt, ExampleRepository $exampleRepository, AttemptRepository $attemptRepository): Response
    {
        $this->denyAccessUnlessGranted('VIEW', $attempt);

        return $this->render('attempt/show.html.twig', [
            'attemptRepository' => $attemptRepository,
            'att' => $attempt->setEntityRepository($attemptRepository),
            'examples' => $exampleRepository->findByAttempt($attempt),
            'exR' => $exampleRepository,
        ]);
    }

    /**
     *@Route("/{id}", name="attempt_solve", requirements={"id": "\d+"})
     */
    public function solve(Attempt $attempt, ExampleRepository $exampleRepository, AttemptRepository $attemptRepository): Response
    {
        if (!$this->isGranted('SOLVE', $attempt)) {
            if ($this->isGranted('VIEW', $attempt)) {
                return $this->redirectToRoute('attempt_show', ['id' => $attempt->getId()]);
            }
            throw $this->createAccessDeniedException();
        }

        $exampleRepository->findLastUnansweredByAttemptOrGetNew($attempt);

        return $this->render('attempt/solve.html.twig', [
            'jsParams' => [
                'attData' => $attempt->setEntityRepository($attemptRepository)->getData(),
                'attempt_answer' => $this->generateUrl('attempt_answer', ['id' => $attempt->getId()]),
                'showAttemptUrl' => $this->generateUrl('attempt_show', ['id' => $attempt->getId()]),
            ],
            'att' => $attempt,
        ]);
    }

    /**
     *@Route("/last", name="attempt_last")
     */
    public function last(AttemptRepository $attemptRepository): Response
    {
        if ($attempt = $attemptRepository->findLastActualByCurrentUser()) {
            return $this->redirectToRoute('attempt_solve', ['id' => $attempt->getId()]);
        }

        return $this->redirectToRoute('attempt_index');
    }

    /**
     *@Route("/new", name="attempt_new")
     */
    public function new(AttemptRepository $attemptRepository): RedirectResponse
    {
        return $this->redirectToRoute('attempt_solve', [
            'id' => $attemptRepository->getNewByCurrentUser()->getId(),
        ]);
    }

    /**
     *@Route("/{id}/answer", name="attempt_answer", methods="POST")
     */
    public function answer(Attempt $attempt, Request $request, ExampleRepository $exampleRepository, EntityManagerInterface $entityManager, AttemptRepository $attemptRepository): JsonResponse
    {
        if (!$this->isGranted('ANSWER', $attempt)) {
            return $this->json(['finish' => true]);
        }

        $example = $exampleRepository->findLastUnansweredByAttempt($attempt);
        $answer = (float) $request->request->get('answer');
        $example->setAnswer($answer);
        $entityManager->flush();

        $finish = !$this->isGranted('SOLVE', $attempt);

        if (!$finish) {
            $exampleRepository->getNew($attempt);
        }

        return $this->json([
            'isRight' => $example->isRight(),
            'finish' => $finish,
            'attData' => $attempt->setEntityRepository($attemptRepository)->getData(),
        ]);
    }

    /**
     *@Route("/{id}/profile", name="attempt_profile")
     */
    public function profile(Attempt $attempt, ProfileRepository $profileRepository, AttemptRepository $attemptRepository): Response
    {
        $this->denyAccessUnlessGranted('VIEW', $attempt);
        $profile = $attempt->getSettings()->setEntityRepository($profileRepository);

        return $this->render('attempt/profile.html.twig', [
            'jsParams' => [
                'canEdit' => false,
            ],
            'profile' => $profile,
            'form' => $this->createForm(SettingsType::class, $profile)->createView(),
            'att' => $attempt->setEntityRepository($attemptRepository),
        ]);
    }
}

templates/attempt/index.html.twig
{% extends 'main.html.twig' %}

{% block title %}
    Архив попыток
{% endblock %}

{% block main %}
    <div class="row">
        <h1>Архив попыток</h1>
        {{ include("attempt/index_table.html.twig") }}
    </div>
{% endblock %}

{%block javascripts%}
    {{parent()}}
    <script src="/js/jquery.datatables.min.js"></script>
    <script>
        $("table").DataTable({
            ordering: false,
            searching: false,
            data: {{ processAttempts(attempts)|reverse|json_encode|raw }},
            deferRender: true,
            pageLength: 50,
            language: {{ include("attempt/language.json.twig") }}
        });
    </script>
{% endblock %}

templates/attempt/index_table.html.twig
<table class="table table-striped tbl-bordered">
    <thead class="thead-dark">
        <th>№</th>
        <th>Начало попытки</th>
        <th>Конец попытки</th>
        <th>Настройки попытки</th>
        <th>Использовано времени</th>
        <th>Решено примеров</th>
        <th>Ошибок</th>
        <th>Оценка</th>
    </thead>

    <tbody></tbody>
</table>

templates/attempt/language.json.twig
{
    "decimal": "",
    "emptyTable": "Нет начатых попыток",
    "info": "Показано с _START_ по _END_ из _TOTAL_ попыток",
    "infoEmpty": "Показано с _START_ по _END_ из _TOTAL_ попыток",
    "infoFiltered": "(Отфильтровано из _MAX_ попыток)",
    "infoPostFix": "",
    "thousands": ",",
    "lengthMenu": "Показать _MENU_ попыток",
    "loadingRecords": "Идёт загрузка...",
    "search": "Поиск:",
    "zeroRecords": "Соответствующих записей не найдено",
    "paginate": {
        "first": "В начало",
        "last": "В конец",
        "next": "Вперед",
        "previous": "Назад"
    },
    "aria": {
        "sortAscending": "",
        "sortDescending": ""
    }
}

templates/attempt/profile.html.twig
{%extends "profile/edit.html.twig"%}

{%set h="Настройки попытки №"~att.number%}
{%block title h%}
{%block main_heading h%}

{%block back_link%}
<a href="{{path("attempt_show", {"id": att.id})}}">Назад к попытке №{{att.number}}</a>
{%endblock%}

{%block advanced_parameters ""%}
{%block save_button ""%}
{%block delete_button ""%}

templates/attempt/show.html.twig
{%extends 'main.html.twig'%}

{%block title att.title%}

{%block main%}
<div class="attempt-show">
	{% set attempt = att %}
	{% set task = attempt.task %}
	{% if task and is_granted('SOLVE', task) %}
<h1><a href="{{ path('homework_index') }}">Задание</a></h1>
<ul>
	<li><a href="{{ path('settings_show', {'id': task.settings.id}) }}">{{ task.settings.description }}</a></li>
	<li>Выполнено {{ attemptRepository.countDoneByCurrentUserAndTask(task) }} из {{ task.timesCount }} попыток.</li>
	<li><a href="{{ path('homework_solve', {'id': task.id}) }}" role="button">Продолжить решение задания</a></li>
</ul>
{% endif %}
	<div class="attempt-show-statistic">
<h1>Статистика</h1>

<ul class="list-group">
	<li>Начало попытки: {{att.addTime}}</li>
	<li>Конец попытки: {{att.finishTime}}</li>
<li>Затраченное время: {{att.solvedTime.minSecFormat}} из {{att.maxTime.minSecFormat}}</li>
	<li>Решено примеров: {{att.solvedExamplesCount}} из {{att.examplesCount}}</li>
<li>Секунд/пример: {{att.averSolveTime.timestamp}}</li>
<li>Ошибок: {{att.errorsCount}}</li>
	<li>Оценка: {{att.rating}}</li>
	<li>Настройки попытки: <a href="{{path("attempt_profile", {"id": att.id})}}">{{ att.settings.description }}</a></li>
</ul>
</div>

<div class="row attempt-show-extbl">
<h1>Примеры</h1>

<table class="table table-striped table-bordered">
	<thead class="thead-light">
		<th>№</th>
		<th>Пример</th>
		<th>Ответ</th>
<th>Время (сек)</th>
	</thead>
<tbody>
	{%for ex in examples|reverse%}
{%set ex=ex.setER(exR)%}
{%if not ex.isRight%}
<tr>
<td colspan="4">
<h6 class="error">{{(ex.answer is not null) ? "Ошибка №"~ex.errorNum : "Пример не решен"}}</h6>
</td>
</tr>
{%endif%}
	<tr class="{{not ex.isRight ? "error" : ""}}">
		<td>{{ex.number}}</td>
		<td>{{ex}}</td>
		<td>{{ex.answer ?? '-'}}</td>
<td>{{ex.solvingTime ? (ex.solvingTime.timestamp ?: "-") : '-'}}</td>
	</tr>
{%else%}
<tr>
<td colspan="4">Нет Примеров в попытке</td>
</tr>
	{%endfor%}
</tbody>
</table>
</div>
</div>
{%endblock%}

templates/attempt/solve.html.twig
{%extends 'main.html.twig'%}

{%block title att.title%}

{% block actual_homeworks %}{% endblock %}

{%block main%}
<div class="attempt-solve">
<form>
<h1>Пример №<span id="num">*</span></h1>
<div class="row example-area">
<span>
<b><span id="str">* + *</span> =</b>
<input type="text" name="" id="" class="{#form-control#}" required="required" pattern="\d+([.]\d+)?">
</span>
</div>

<button type="submit" class="btn btn-primary btn-lg">Ответить</button>
</form>

<div class="attempt-solve-statistic">
<h2>Статистика</h2>
<ul class="list-group">
<li class="list-group-item">Ошибок: <span id="errors">*</span></li>
	<li class="list-group-item">Осталось времени: <span id="timeRem">*</span></li>
	<li class="list-group-item">Осталось примеров: <span id="exRem">*</span></li>
	<li class="list-group-item">Настройки попытки: <a href="{{path("attempt_profile", {"id": att.id})}}">{{att.settings.description}}</a></li>
	</ul>
</div>
</div>
{%endblock%}

{%block javascripts%}
{{parent()}}
<script src="/js/helper.js"></script>
<script src="/js/app/attempt/solve.js"></script>
<script>
</script>
{%endblock%}